/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package rhcad.touchvg.core;

public final class GiPathNode {
  public final static GiPathNode kGiCloseFigure = new GiPathNode("kGiCloseFigure", 1);
  public final static GiPathNode kGiLineTo = new GiPathNode("kGiLineTo", 2);
  public final static GiPathNode kGiBezierTo = new GiPathNode("kGiBezierTo", 4);
  public final static GiPathNode kGiQuadTo = new GiPathNode("kGiQuadTo", 8);
  public final static GiPathNode kGiMoveTo = new GiPathNode("kGiMoveTo", 6);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GiPathNode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GiPathNode.class + " with value " + swigValue);
  }

  private GiPathNode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GiPathNode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GiPathNode(String swigName, GiPathNode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GiPathNode[] swigValues = { kGiCloseFigure, kGiLineTo, kGiBezierTo, kGiQuadTo, kGiMoveTo };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

